package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class AddFoodItemController {
	@FXML
	private TextField FoodName;
	@FXML
	private TextField IDnumber;
	@FXML
	private TextField Calories;
	@FXML
	private TextField Fat;
	@FXML
	private TextField Carbs;
	@FXML
	private TextField Fiber;
	@FXML
	private TextField Protein;
	@FXML
	private Button AddFoodItem;

	// Event Listener on Button[#AddFoodItem].onAction
	@FXML
	public void addFoodItemToFoodList(ActionEvent event) {
		// TODO Autogenerated
	}
}
