package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class AnalyzeMealController {
	@FXML
	private TextField TotalCaloris;
	@FXML
	private TextField TotalFat;
	@FXML
	private TextField TotalCarbs;
	@FXML
	private TextField TotalFiber;
	@FXML
	private TextField TotalProtein;
	@FXML
	private Button AnalyzeTotalMeal;

	// Event Listener on Button[#AnalyzeTotalMeal].onAction
	@FXML
	public void totalNutrientsInMeal(ActionEvent event) {
		// TODO Autogenerated
	}
}
